name: deus ex machina
favicon: null
layout_spectrum: 0.8740352692548186
typography_spectrum: 0.07663706061430275
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.497090490302071
  lightness: 0.2660074003506452
  saturation: 0.87483060057275
  rhythmicContrast: 0.6032720489893109
purpose: []
